// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtT_Imj1ha0q0ogPHNmAqfkgEplH-kFXM',
    appId: '1:670319805278:web:33f5359bc7101414cf85cf',
    messagingSenderId: '670319805278',
    projectId: 'shopping-app-cf853',
    authDomain: 'shopping-app-cf853.firebaseapp.com',
    storageBucket: 'shopping-app-cf853.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC0X57H4L_osjvq8kEhjXGaWRiGIr8ePM',
    appId: '1:670319805278:android:0a0a22efce6bc2d8cf85cf',
    messagingSenderId: '670319805278',
    projectId: 'shopping-app-cf853',
    storageBucket: 'shopping-app-cf853.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtT_Imj1ha0q0ogPHNmAqfkgEplH-kFXM',
    appId: '1:670319805278:web:f20b701e517f2450cf85cf',
    messagingSenderId: '670319805278',
    projectId: 'shopping-app-cf853',
    authDomain: 'shopping-app-cf853.firebaseapp.com',
    storageBucket: 'shopping-app-cf853.firebasestorage.app',
  );
}
